spring:
  application:
    name: testing
  datasource:
    url: jdbc:mysql://database:3306/zoo
#    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}