spring:
  application:
    name: testing
  datasource:
    url: jdbc:mysql://localhost:3306/zoo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
bumPoo: ${TEST}